name: get_secure_storage_plus
description: A secure version of get_storage, a fast, extra light and synchronous key-value storage written entirely in Dart
version: 1.0.1
homepage: https://github.com/bousalem98/get_secure_storage_plus

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #get: ">=4.0.0 <6.0.0"
  get: any
  path_provider: ^2.1.2
  cryptography: ^2.7.0
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
